apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '8'
  generation: 20
  labels:
    app: bigdata-springboot-docker-demo-v2
  name: bigdata-springboot-docker-demo-v2
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bigdata-springboot-docker-demo-v2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bigdata-springboot-docker-demo-v2
    spec:
      containers:
        - image: 'docker.sz-shuwei.com/gs-spring-boot:<BUILD_TAG>'
          imagePullPolicy: Always
          name: bigdata-springboot-docker-demo-v2
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: bigdata-docker
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

